import {
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiPostgresql,
  SiTypescript,
  SiTailwindcss,
  SiGithubactions,
  SiGraphql,
  SiJavascript,
  SiGit,
  SiPostman,
  SiRazorpay,
  SiZapier,
} from "react-icons/si";
import { FaAws } from "react-icons/fa";
import { IconType } from "react-icons";

export const skillIconMap: Record<string, IconType> = {
  "React.js": SiReact,
  "Next.js": SiNextdotjs,
  "Node.js": SiNodedotjs,
  Express: SiExpress,
  MongoDB: SiMongodb,
  PostgreSQL: SiPostgresql,
  TypeScript: SiTypescript,
  TailwindCSS: SiTailwindcss,
  "AWS EC2": FaAws,
  S3: FaAws,
  CloudFront: FaAws,
  "GitHub Actions (CI/CD)": SiGithubactions,
  GraphQL: SiGraphql,
  JavaScript: SiJavascript,
  Git: SiGit,
  Postman: SiPostman,
  Razorpay: SiRazorpay,
  Zapier: SiZapier,
};
